### ISSUE TITLE
Running all unit tests at once - System.InvalidOperationException : Sequence contains more than one matching element

### ISSUE THREAD

**Issue by GWawrzeniecki** [daryllabar/XrmUnitTest#155]
Hello,
Sometimes when I run all unit tests simultaneously I experience the following error 
```
  Message: 
System.InvalidOperationException : Sequence contains more than one matching element
---- System.InvalidOperationException : Sequence contains more than one matching element

  Stack Trace: 
GenericMethodCaller.ThrowInnerException(TargetInvocationException ex)
GenericMethodCaller.InvokeLocalCrmDatabaseStaticMultiGenericMethod(LocalCrmDatabaseInfo info, String methodName, BindingFlags bindingFlags, Object[] typesOrLogicalNames, Object[] parameters)
LocalCrmDatabaseOrganizationService.RetrieveMultipleInternal(QueryExpression qe)
LocalCrmDatabaseOrganizationService.RetrieveMultiple(QueryBase query)
Extensions.GetFirstOrDefault(IOrganizationService service, String logicalName, Object[] columnNameAndValuePairs) line 627
LocalCrmDatabaseOrganizationService.CreateRequiredEntitiesIfNeeded()
TestBase.GetLocalCrmDatabaseOrganizationService(String organizationName, Guid impersonationUserId)
TestBase.GetOrganizationService(String organizationName, Guid impersonationUserId)
ServiceProviderBuilder.ctor()
<>c.<ImageShouldMergePreImages>b__5_0(IOrganizationService _) line 160
AgnosticTest.Test(IOrganizationService service) line 66
TestActionTimer.Time(Action actionToTime, String actionDescription)
TestMethodClassBaseDLaB.Test(ITestLogger logger)
TestMethodClassBase.Run() line 19
ImageTests.ImageShouldMergePreImages() line 179
----- Inner Stack Trace -----
Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
TableLocator.FindAffectedTables(IDatabase database, IExecutionPlan plan)
CommandExecutor.ExecuteQuery[T](IExecutionPlan`1 plan, IExecutionContext context)
TableQuery`1.GetEnumerator(IDictionary`2 parameters, Transaction transaction)
List`1.ctor(IEnumerable`1 collection)
Enumerable.ToList[TSource](IEnumerable`1 source)
LocalCrmDatabase.ReadEntities[T](LocalCrmDatabaseOrganizationService service, QueryExpression qe)
```
Which probably happens here

![image](https://github.com/user-attachments/assets/87a8da25-ad56-4114-91f9-33e7d5bfc492)

All my tests are wrapped in TestMethodClassBaseDLaB.

Other issue I experienced is when `Ids struct` have Id field which is null the `TestMethodClassBaseDLaB` class throws null reference exception in method `InitializeEntityIds`.

I created following class to reduce clutter in the code

![image](https://github.com/user-attachments/assets/f4073abf-bdc5-4305-898f-a13c7114a8b0)

which I can use like this

![image](https://github.com/user-attachments/assets/5f069cf0-e750-4cbf-b9c8-507b148d420f)

but I have to initialize each Id field in my Ids struct

**Comment by daryllabar** [comment]
You've got multiple issues, but lets tackle them one at a time:

### Defining Ids / Use of TestMethodClassBase
The only time you'd want to use the `TestMethodClassBase` class is if you want your test to be testable against both the in-memory XrmUnitTest Fake IOrganizationService, and to be able to run against an actual environment.  As such, the Ids need to be explicitly hard coded to specific Guids in order for the auto-cleanup feature of the TestMethodClassBase to work.  So your "work around" is really the entirely wrong approach to take, and the reason that it's hard to do, is because you're not supposed to be doing it 😉.  Also using the Typed version of the `Id`'s makes life easier as well:
```cs
private struct Ids
{
    public static readonly Id<Account> Account = new Id<Account>("A8C3DD73-4796-4755-8C7D-186F1A3BE6A5");
    public static readonly Id<Contact> Contact = new Id<Contact>("08ABE111-D02D-46C7-B6FA-1FD0177CDAA4");
}
```
In your test example, there is no reason to be using the Test method class base at all.  You don't even need an IServiceProvider or an IOrganizationService.  Something like this would just fine:
```
[Fact]
public void ImageShouldLoadPreImage()
{
    // Arrange
    var preImage = new Entity();
    var context = new PluginExecutionContextBuilder()
        .WithPreImage(preImage, "PreImage").Build();

    // Act
    var image = new Image(context);

    // Assert
    image.PreImage.Should().Be(preImage);
    image.HasPreImage.Should().BeTrue();
}

### The Actual Error
This one is a little hard to figure out, but from the stack trace, it looks like there might be more than one EarlyBound class for the same logical name?  Did you maybe miss a partial keyword somewhere?

**Comment by GWawrzeniecki** [comment]
First of all, thank you very much for your help.
The reason I wrap each test method in `TestMethodClassBase ` is because of that error but obviously I was wrong.
My project is quite new and I have one test method that can be run against local or real CRM environment. 
In my post I was unclear, this error happens only when I run all the tests simultaneously, when one by one or by unit test class it's not the case. (That's why I wrapped everything). 
I've generated early bounds using your tool (Early bound generator  V2).
I have generated 8 C# early bound classes and each one has only one class type, like this

![image](https://github.com/user-attachments/assets/2c4ed213-9346-4bfc-a149-d4b5912cd3d8)

Looking forward to hearing from you

**Comment by daryllabar** [comment]
The IOrganizationService itself is not thread safe, any chance that you are reusing a service across tests?

**Comment by GWawrzeniecki** [comment]
I use `ServiceProviderBuilder` and `OrganizationServiceBuilder` across the tests.

For example, this piece of code 
![image](https://github.com/user-attachments/assets/0a8c344c-000d-48db-8598-833eb0ab4d98)
Gives me the following exception when run  simultaneously 

![image](https://github.com/user-attachments/assets/a2ba7ba5-75e5-4a0b-913d-88fc19347802)

but when I change it to do not use `ServiceProviderBuilder` the exception is gone

![image](https://github.com/user-attachments/assets/292e3e04-6acd-44c3-9125-fef2f6463831)

**Comment by daryllabar** [comment]
Ok, I'll have to debug this at some point.  And you're just running this using the text explorer in visual studio, and when you say you run it "simultaneously" you're just running the test using the Run All tests play button?  And you're using XUnit for your testing framework?

**Comment by GWawrzeniecki** [comment]
Yes, Test Explorer - Run All tests in View and XUnit framework.

**Comment by daryllabar** [comment]
I don't see any call to set your Test Settings.  If I run your code, i get this error:
```
DLaB.Xrm.Test.Exceptions.NotConfiguredException: 'User Test Config Path has not been configured.  Call DLaB.Xrm.Test.TestSettings.UserTestConfig.Configure first before getting the UserTestConfigPath.'
```

Is that your own `ServiceProviderBuilder`, or is that the `DLaB.Xrm.Test.Builders.ServiceProviderBuilder`?

Also, what version of the XrmUnitTest are you running?

**Comment by GWawrzeniecki** [comment]
> I don't see any call to set your Test Settings. If I run your code, i get this error:

My every test class inheritance from `XrmTestBase`

![image](https://github.com/user-attachments/assets/a466c5b2-2231-46d2-b742-59ac2b4943470

> Is that your own ServiceProviderBuilder, or is that the DLaB.Xrm.Test.Builders.ServiceProviderBuilder?

`DLaB.Xrm.Test.Builders.ServiceProviderBuilder`

> Also, what version of the XrmUnitTest are you running?

3.3.0.67

**Comment by daryllabar** [comment]
Get 3.3.0.68 and try again.

**Comment by GWawrzeniecki** [comment]
It's fixed! 
Thank you very much
