### ISSUE TITLE
Most of the requests are not implemented

### ISSUE THREAD

**Issue by rebulanyum** [daryllabar/XrmUnitTest#43]
Hello.

I've installed XrmUnitTest.2016 package from nuget into my unit test project. And ran a unit test that executes RetrieveRequest against OrganizationService. Since I've configured it to use the FakeIOrganizationService I get an NotImplementedException. I realized that the exception is coming from [LocalCrmDatabaseOrganizationServiceExecute.cs line 36](https://github.com/daryllabar/XrmUnitTest/blob/master/DLaB.Xrm.LocalCrm.Base/LocalCrmDatabaseOrganizationServiceExecute.cs#L36) . 

So, why I can't even retrieve any record from in memory db? Have you implemented it else where? Or how can I retrieve records with your library?

**Comment by daryllabar** [comment]
Normally I do service.Retrieve, which is different than service.Execute(new RetrieveRequest()).  I've implemented the function and updated the NuGet Package.  Get latest and it should be working.

Thanks for bringing this up and let me know if you have any other issues.

**Comment by rebulanyum** [comment]
Thank you for the fast response. It solved my problem temporarily but facing another issue with the same topic:

And this time I cannot execute RetrieveRelationshipRequest against the FakeOrganizationService. The real problem is that there are many requests of CRM that it's not being implemented yet.

By the way; I wanted to advice you to write tests with the CrmContext class which is generated by CRM. For example;

```csharp
    var service = LocalCrmDatabaseOrganizationService.CreateOrganizationService(LocalCrmDatabaseInfo.Create<CrmContext>(Guid.NewGuid().ToString()));
    using (var context = new CrmContext(service))
    {
       var firstContact = (from contact in context.ContactSet
                           select contact).First();
       context.LoadProperty(firstContact, "business_unit_contacts");
    }

The line with `context.LoadProperty(firstContact, "business_unit_contacts");` will throw a NotImplementedException. Just as I told before.

**Comment by rebulanyum** [comment]
And do you think I should create another issue or will you return this issue to "Open" state.

**Comment by daryllabar** [comment]
I actually tend not to write Linq To CRM statements using the context because I've seen "unexplainable" issues with it in live versions of CRM.  It is very rare, but I've seen it happen.  This is why the two requests that you've mentioned haven't been implemented, because I haven't needed them and no one has requested them.  Now enter you ;)

Also, I see that you sent a Skype Request,  If you're wanting to chat about the XrmUnitTest framework, ask me questions, etc, Hit me up on Gitter.  I've sent you a link for this project's room.

In the mean time, I've moved this separate request to another task and will be implementing it in the near future.

**Comment by daryllabar** [comment]
And a P.S.  If you use the Early Bound Generator from the XrmToolBox, it has fields for the relationships:

```context.LoadProperty(firstContact, Contact.Fields.business_unit_contacts);```

If you wanted to use auto-completion.

**Comment by rebulanyum** [comment]
Sorry but no, I haven't sent you a skype request or I've made a mistake :)

Thank you by the way.
