### ISSUE TITLE
Creating test records with not standard default entity attribute (Name)

### ISSUE THREAD

**Issue by janiskulj** [daryllabar/XrmUnitTest#51]
When creating entity records for tests in CRM, library tries to set default (Name) attribute. If default entity attribute is not defined as standard (xxx_name) create fails.

**Comment by daryllabar** [comment]
Couple steps... I may think about making this a little easier going forward, but for now, this is the current method to handle this.

2 options.  
1. You hate the whole defaulting of the name, so override the GetIOrganzationService Method of the TestMethodClassBase, and skip the EntiyNameDefaulted:

Current:
``` C#
protected virtual IOrganizationService GetIOrganizationService()
{
    return GetOrganizationServiceBuilder(GetInternalOrganizationServiceProxy()).
        WithEntityNameDefaulted((e, i) => GetUnitTestName(i.MaximumLength)).
        AssertIdNonEmptyOnCreate().
        WithDefaultParentBu().Build();
}
```
New:
``` C#
protected virtual IOrganizationService GetIOrganizationService()
{
    return GetOrganizationServiceBuilder(GetInternalOrganizationServiceProxy()).
        AssertIdNonEmptyOnCreate().
        WithDefaultParentBu().Build();
}
```

2. You like the names defaulted, just want to define the non-standard names.  In your TestMethodBase Class, you need to override the GetOrganizationServiceBuilder() and give it your own OrganizationServiceBuilder.  In your own OrganziationServiceBuilder that you are returning, you need to override the GetPrimaryFieldInfo method, and you need to override your non-standard entities:

``` C#
private Dictionary<string,string> _entityNameMappings;
public virtual PrimaryFieldInfo GetPrimaryFieldInfo(string logicalName)
{
    var info = EntityHelper.GetPrimaryFieldInfo(logicalName);
    string attName;
    if(_entityNameMappings.TryGetValue(logicalName, out attName)){
        info.AttributeName = attName;
    }
    return info
}
```

**Comment by janiskulj** [comment]
I cholse second option and works great. Thank you,

**Comment by daryllabar** [comment]
Thanks for using the tool janiskulj.  Let me know how it goes.
