### ISSUE TITLE
Fake Opportunity with ParentAccountId and ParentCustomerId

### ISSUE THREAD

**Issue by ovinophile** [daryllabar/XrmUnitTest#52]
When trying to set up unit tests with a faked Opportunity, I've found it's not possible to set both "parentaccountid" and "parentcontactid" on the entity. It appears that the AutoPopulateOpportunityFields method in LocalCrmDatabaseOrganizationService.cs prevents this, allowing only one or the other to be populated, and only via "customerid". Yet CRM does apparently allow an Opportunity to have both fields populated at once.

**Comment by daryllabar** [comment]
Looks like the CustomerId is the ParentAccountId if it is set, and the ParentContactId if it is set and the parentAccound id is not.  Nulling out the Customer Id will null out the associated parent attribute as well, and nulling out the ParentAccountId will update the CustomerId to be the ParentContactId if it is set.

**Comment by daryllabar** [comment]
Can you try the latest pre-release and see if that resolves your issue?
