### ISSUE TITLE
Questions about XrmUnitTest

### ISSUE THREAD

**Issue by hakima25** [daryllabar/XrmUnitTest#54]
Hello,
This is the first time i am using Unit tests for plugins and I was interested in your tool. I was wondering if we could use it with Dynamics 365 because with  Nuget Package Manager we only have DLab.Xrm.2015 and  DLab.Xrm.2016.
I've installed XrmUnitTest.2016 package from nuget into my unit test project but I have a problem, I do not know how to run the plugin in the ACT part because the Execute method of my plugin is not static and it does not use a IOrganizationService service as a parameter but an IServiceProvider !!!
what should i do in this case ?

Thank you for your help

**Comment by daryllabar** [comment]
I'm currently trying to find the time to change how the testing is structured, hence, the lack of a 9.0 version of XrmUnit Test currently.

But with that being said, you can still use the latest version of the dlls, you'll just need to add some binding redirects.

As far as your unit testing, check out the Example project in the code, just create your plugin, and call the execute method on it.  You can use a PluginExecutionContextBuilder to build what you need to fake everything out.

        private void Test(IRegisteredEventsPlugin plugin)
        {
            //
            // Arrange
            //
            var contact = new Contact { MobilePhone = "A-1-B-2-C-3" }; // Create Contact to use as target
            var context = new PluginExecutionContextBuilder(). // Create Context Which is required by the service provider, which is required by the plugin
                WithRegisteredEvent(plugin.RegisteredEvents.First(e => e.EntityLogicalName == Contact.EntityLogicalName)). // Specifies the plugin event to use in the context
                WithTarget(contact).Build(); // Sets the Target
            var provider = new ServiceProviderBuilder().
                WithContext(context).Build();
            //
            // Act
            //
            plugin.Execute(provider); // Executes the Plugin


            //
            // Assert
            //


            Assert.AreEqual("123", contact.MobilePhone);
        }
