### ISSUE TITLE
DLaB.Xrm.2016

### ISSUE THREAD

**Issue by capuanodanilo** [daryllabar/XrmUnitTest#55]
Hi Daryl,
where I found the source code only DLaB.Xrm.2016 project?

Regards,

**Comment by daryllabar** [comment]
There is no need for a 2016 version of the source, since your project will reference whatever version of the sdk that you want

**Comment by capuanodanilo** [comment]
Yes, but I want refer to only project necessary to customize it...what is the source code?

**Comment by capuanodanilo** [comment]
Do you have a tutorial how use it?

**Comment by daryllabar** [comment]
Are you asking what does it do, or are you asking how do you use it, or where the source code is for it?

**Comment by capuanodanilo** [comment]
Source Code and How use it :-)

**Comment by daryllabar** [comment]
The source itself is in this GitHub repository.  (That's probably a no-no, but it was easier to manage) There is an example plugin that references it's plugin base.  It also has a whole bunch of Extension methods on the IOrganizationService that simplifies QueryExpressions.  A source only nuget package brings in the source itself into your project.  You can edit it however you like, but when you upgrade, NuGet will keep files you've edited.

**Comment by capuanodanilo** [comment]
Thanks
