### ISSUE TITLE
FullNameFormat Usage

### ISSUE THREAD

**Issue by ovinophile** [daryllabar/XrmUnitTest#76]
A couple things I'm running into using the FullNameFormat setting:

1. Finding that I have to add the "CrmSystemSettings.FullNameFormat" key-value to App.config instead of UnitTestSettings.User.config in order for it to apply. Or am I doing something wrong here?

2. When I provide a format of "L, F M", I end up with an extra space at the end of the full name when there's no middle name: "{last}, {first} ". Looks like it's because it only removes any extra space after M when middle name is empty, but leaves the extra space after F in that case.

**Comment by daryllabar** [comment]
For Issue 1.  Have you called TestSettings.UserTestConfigPath.Configure() prior to running your test?   This is what wires up the user.config to read the values.  If you don't, then it will read from the app.config by default, so hopefully yes, you are doing something wrong.

For 2, I have a bug fix coming shortly.

Fo

**Comment by daryllabar** [comment]
Thanks for submitting the bug!
